### ISSUE TITLE
Gamma zone rule sets

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#249]
Create the flexibility to enforce certain parameters on certain zones w.r.t Gamma structures, types, keep-out radii, quantity limits, etc.
Current rules enumerated to date include:
 - zone wide limit on terminals (currently a field in DB, but does it work?!)
 - Tech level limit of structures
 - Structure type limits (only allow certain structures/categories, or disallow certain structures/cats)
 - Distance limits/restrictions (most are constants right now)

Being able to control this down to each zone, and apply any of these with particular parameters would be desirable.
Probably there will be 3-4 "templates" of rules that will be applied, a template system to apply rules to a zone would also be desirable (like itemshop presets).

**Comment by naHrej** [comment]
The database defined zone-wide limit on terminals appears to be implemented in the checks for deployment. I'll do some testing to verify tomorrow but a precursory look at the code indicates that we're in a good place for point 1.

https://github.com/OpenPerpetuum/PerpetuumServer/blob/65e25c31774b8fabb49667dcc2c4f4f82949a94d/src/Perpetuum/Zones/PBS/PBSHelper.cs#L130-L135
