### ISSUE TITLE
Blind Terminal Chat to characters that shouldnt be able to dock

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#309]
On Beta outposts - blind terminal chat all players docked at outpost not in same corp, or not of some relation (based on outpost setting on lock)

Procedure:
for players docked at outpost
    if character not in corp or of locked-out-relation
        blind terminal chat to character

**Comment by aqpanaciy** [comment]
Work plan:

- [x] Separate the docking/undocking with the station and updating the channel for class _DockingBase_;
- [x] Add _DockingBase list_ of online characters on the station for a subsequent channel update;
- [x] Add check of docking and **going online** characters (always add them to the _DockingBase list_);
- [x] Develop a solution to the problem - what to do when changing the relationship between corporations or changing access control for the outposts/terminal;
- [x] Test for public terminals / Beta outposts / Gamma terminals;
- [x] Update and test for resent Spark-Teleport.

**Comment by aqpanaciy** [comment]
It was decided to use a *simpler* solution.

**Comment by aqpanaciy** [comment]
The solution was added and applied in patch p31.
