### ISSUE TITLE
New Player Starting NIC/EP -> DB.  lookup on start

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#310]
Starting nic is hardcoded
``` 
namespace Perpetuum.Zones.Teleporting.Strategies
{
    public class TrainingExitStrategy : ITeleportStrategy
    {
        private const double CHARACTER_START_CREDIT = 20000;
```
EP is 0.  

Enter new parameters into game-settings table?
Lookup on tutorial exit?

**Comment by Ghroom** [comment]
Is there already a table to receive these paramaters?

**Comment by MikeJeffers** [comment]
> Is there already a table to receive these paramaters?

No - but maybe depending how you want to interpret the use of other existing tables.

In general, it will be easier to make your own and make it generic enough to house other global constants that might be floating around the server source. :)

**Comment by aqpanaciy** [comment]
https://github.com/OpenPerpetuum/PerpetuumServer/pull/459 added the ability to configure these parameters.
