### ISSUE TITLE
Logging - Syndicate Shop 

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#316]
PurchaseCount only grabs the most recent purchase quantity
We need to capture a log of purchases that ideally contain:
Definition, quantity, shop-of-origin, datetime
For all syndicate shop items
Into a new table of some sort

**Comment by Ghroom** [comment]
You can already retrieve the transactions made in the item shop.
Do you need to also  know the terminal (shop-of-origin)?

**Comment by MikeJeffers** [comment]
> You can already retrieve the transactions made in the item shop.
> Do you need to also know the terminal (shop-of-origin)?

You are right, this is all captured in the CharacterTransactions.  
You can close this issue with that note.  We aren't missing any data as this issue was initially worried about.

**Comment by Ghroom** [comment]
If needed, here is the query: 
SELECT TOP (1000) 
	  trans.[transactiontype]
      ,trans.[amount]
      ,trans.[transactiondate]
      ,trans.[definition]
      ,trans.[quantity]
	,trtyp.[name]
  FROM [perpetuumsa].[dbo].[charactertransactions] trans
  left join [perpetuumsa].[dbo].[transactiontypes] trtyp on trtyp.value = trans.transactiontype
  where [transactiontype]=73
