### ISSUE TITLE
Renaming Gamma Terminal throws error_EntityNotFound

### ISSUE THREAD

**Issue by naHrej** [OpenPerpetuum/PerpetuumServer#336]
Renaming a new Gamma Terminal or renaming in quick succession without reopening the map throws a error_EntityNotFound to the client. 
![image](https://user-images.githubusercontent.com/16448026/119610271-4b905f00-be3c-11eb-801a-42903c4c0ec4.png)

**Comment by MikeJeffers** [comment]
Closed by https://github.com/OpenPerpetuum/PerpetuumServer/pull/377
