### ISSUE TITLE
NPC State: npc freeze/no-movement

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#342]
Tends to occur when hostiles are too far, unable to resolve path, but sometimes in other cases - unclear on the edges of the problem.

NPCs should always fallback into a state that is somewhat logical.  Idle/no-movement is not acceptable when being aggressed.

**Comment by aqpanaciy** [comment]
I have been [studying](https://youtu.be/j_RNaO4sIdo) this problem for a long time. There are at least three reasons why NPCs don't move while aggro:
 * if the player does not move, then according to this [condition](https://github.com/OpenPerpetuum/PerpetuumServer/blob/b9cb19b3e7d609fea6a07cb3a7551654e2db44dd/src/Perpetuum/Zones/NpcSystem/Npc.cs#L512), the entire analysis is skipped;
 * [here](https://github.com/OpenPerpetuum/PerpetuumServer/blob/b9cb19b3e7d609fea6a07cb3a7551654e2db44dd/src/Perpetuum/Zones/NpcSystem/Npc.cs#L579), when searching for a new path, the NPC stops and if the search fails, it will continue to stand. The old path is not reset, and the NPC tries to move along it at zero speed;
 * for some unknown reason, [here](https://github.com/OpenPerpetuum/PerpetuumServer/blob/b9cb19b3e7d609fea6a07cb3a7551654e2db44dd/src/Perpetuum/Zones/Movements/WaypointMovement.cs#L27) the start and end points of the path coincide, and the vector after normalization has NaN values in components. Accordingly, far Update(...) does not work.

**Comment by aqpanaciy** [comment]
Work plan:

- [x] rework the < **void UpdateHostile(TimeSpan time)** > method to analyse even stationary targets in **AggressorAI**;
- [x] when **stopping** the NPC, reset the path to **NULL**;
- [x] fix **WaypointMovement**;
- [x] сheck other conditions that may cause the NPС to freeze;
- [x] develop a test plan for the changes described above;
- [x] test according to plan.
