### ISSUE TITLE
Increase activation range of PBSEggs

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#386]
Because buildings have a big footprint, and we will move the player to avoid them getting stuck, let's also just allow players to activate them from safer distance.
Design team says: 150m (15)

Relevant code to override: https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Zones/Eggs/Egg.cs#L252

probably breakout a virtual method for this range check and let subclasses override if they want to allow/check different distances.

**Comment by Hunterskull** [comment]
A player can't activate a building from any distance greater than 100 meters. As soon the player is 100 meters away, the interact button forces the player to move within 79 meters of the building and then interacts with the building. The approach functionality overrides the building range even if it's greater than 100 meters
