### ISSUE TITLE
AreaBomb should set a despawn time

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#413]
AreaBombs should probably have *some* despawn timer set (to avoid spamming them and letting them sit indefinitely)
By using: https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Zones/Eggs/Egg.cs#L39
On: https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Zones/Eggs/AreaBomb.cs
Override the `Initialize` method like other eggs: https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Zones/PBS/PBSEgg.cs#L30-L34 or https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Zones/NpcSystem/NpcEgg.cs#L9-L13

**Comment by jeffmaley** [comment]
I add this to my PR for #400

**Comment by MikeJeffers** [comment]
Closed by @jeffmaley on https://github.com/OpenPerpetuum/PerpetuumServer/pull/400
