### ISSUE TITLE
Boss NPC: chat message on player kill

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#446]
Because awesome

**Comment by Ramit110** [comment]
This appears to at least be partially implemented in [this section of the codebase](https://github.com/OpenPerpetuum/PerpetuumServer/blob/9dbb1c92e6efe7ba070f2da579b0ef980416250d/src/Perpetuum/Zones/NpcSystem/NPCBossInfo.cs#L161-L175)

**Comment by MikeJeffers** [comment]
You are correct!  Good catch
